:prodname: Fuse Ignite
:prodversion: 0.1
:imagesdir: images

[[Tutorials]]
== {prodname} Sample Integration Tutorial

{prodname} lets you obtain data from an
application or service, operate on that data if you need to, and then send the 
data to a completely different application or service. You can do all this
without writing code. 

[IMPORTANT]
====
{prodname} is a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features support scope, 
see https://access.redhat.com/support/offerings/techpreview/. 
====

Explore the {prodname} Technology Preview by creating two
sample integrations. For instructions, see:

* <<Twitter-to-Salesforce>>
* <<Salesforce-to-DB>>
// * <<Three-APIs>>

// You can create these sample integrations in any order. 

include::topics/t2sf_intro.adoc[leveloffset=+1]

include::topics/sf2db_intro.adoc[leveloffset=+1]

// include::topicss/3api_intro.adoc[leveloffset=+1]
