[[create-twitter-connection]]
= Create a Twitter connection

A {prodname} connection to Twitter requires registration of
{prodname} as an application that can access Twitter.
If you did not already register {prodname}, see <<register-with-twitter>>. 

After you create a Twitter connection, you can use it in multiple integrations.  

To create a Twitter connection:

. In the left pane, click *Connections* to display available connections. 
Initially, there are no connections. 
. In the upper right, click *Create Connection* to display
{prodname} connection types. 
. Click the *Twitter* connection type. 
. Click *Connect Twitter* to display a Twitter authorization page. 
. Click *Authorize App* to return to {prodname}.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connection. 
For example, enter `*Twitter Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Twitter connection
that uses my Twitter log-in credentials.*`
. In the upper right, click *Create* to see that the connection you 
created is now available. If you entered the example name, you would 
see that *Twitter Connect 1* is now available. 
