// Reused in 
// "t2sf_intro.adoc", "sf2db_intro.adoc"
[#create-salesforce-connection-{context}]
= Create a Salesforce connection

A {prodname} connection to Salesforce requires registration of
{prodname} as an application that can access Salesforce.
ifeval::["{context}" == "t2sf"]
If you did not already register {prodname} see <<register-with-salesforce-{context}>>.
endif::[]

ifeval::["{context}" == "sf2db"]
If you did not already register {prodname}, see <<register-with-salesforce-{context}>>.
endif::[]

After you create a Salesforce connection, you can use it
in multiple integrations.

To create a Salesforce connection:

. In the left pane, click *Connections* to display available connections. 
. In the upper right, click *Create Connection* to display
{prodname} connection types. 
. Click the *Salesforce* connection type. 
. Click *Connect Salesforce* to display a Salesforce authorization page. 
. Click *Authorize App* to return to {prodname}.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connection. 
For example, enter `*SF Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Salesforce connection
that uses my Salesforce log-in credentials.*`
. In the upper right, click *Create* to see that the connection you 
created is now available. If you entered the example name, you would 
see that *SF Connect 1* is now available. 
