[[register-with-sf]]
= Register {prodname} as a Salesforce client

You must register your installation of {prodname} as an application 
that can access Salesforce. 
This lets you create any number of integrations that connect
to Salesforce. In other words, you need to register {prodname}
with Salesforce only once. 

Perform these steps:

. In {prodname}, in the left pane, click *Home*.
. Copy the {prodname} URL from the browser address bar.
. In the left pane, click *Settings*.
. In the *OAuth Client Management* page, to the left of *Salesforce*,
click *>* to display the *Client ID* and *Client Secret* fields.
. In another browser tab, go  to 
https://help.salesforce.com/articleView?id=connected_app_create.htm[Create a Connected App]
 for information and instructions for registering {prodname} with Salesforce.
The main steps you perform are:
.. Log in to Salesforce.
.. Use the *New Connected App* wizard. One of the wizard steps is to provide
a callback URL. Enter your {prodname} URL and append `/api/v1/credentials/callback`. 
For example: 
`https://{prodnameinurl}.192.123.45.6.nip.io/api/v1/credentials/callback`.
.. Make a note of the consumer key and the consumer secret that the 
*New Connected App* wizard provides. 
. On your {prodname} installation *Settings* page, paste the Salesforce 
consumer key into the Salesforce *Client ID* field. 
. On your {prodname} installation *Settings* page, paste the Salesforce 
consumer secret into the {prodname} Salesforce 
*Client Secret* field. 
. Click *Save*.
