[[t2sf-prerequisites]]
= Prerequisites for implementing Twitter to Salesforce integration

To implement a Twitter to Salesforce sample integration:

* In your GitHub account, you must have registered and authorized 
{prodname}. 
+
If you logged in to {prodname} before reading this document, then
you most likely did this when you were prompted to as part of 
logging in to {prodname}. 
+
If you are reading this document before logging in to {prodname},
then you can do one of the following:
+
** Log in to {prodname} and configure your GitHub account when prompted.
** https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/registering-oauth-apps/[Configure your GitHub account now.]
Be sure to save the client ID and client secret in an easily accessible place or
keep the registered app tab open to easily obtain those values. 
When you log in to {prodname} you enter these values when prompted.

* You need a Twitter account.

* You need an account in a Salesforce installation that is used for development.

* Add the `TwitterScreenName` custom field to the Salesforce 
contact object. See the 
https://help.salesforce.com/articleView?id=adding_fields.htm[Salesforce documentation] 
for details, or follow these instructions:

. In Salesforce, go to *Build* > *Customize* > *Contact*. 
. Choose *Fields*. 
. In *Contact Custom Fields & Relationships*, click *New* and add a 
field with these attributes:
.. *Data Type* is *Text*.
.. *Field Label* is *`TwitterScreenName`*.
.. *Field Length* is `15`.
.. *Uniqueness* is *Do not allow duplicate values*.
.. Set: *Set this field as the unique record identifier from an external system.*
. Click *Save*.
