[[Twitter-to-Salesforce]]
= Implement a Twitter to Salesforce Sample Integration

:reuse: t2sf
This sample integration watches Twitter for tweets that mention
a particular Twitter user. When the integration finds such tweets, 
it filters
them so that only those tweets that contain the text you specify cause
the integration to continue. 

For tweets that contain the specified text, the integration compares
the value of the Twitter `screenName` field, which is the Twitter
handle of the user who tweeted, with the value of the
Salesforce `TwitterScreenName_c` field in each contact object
in the Salesforce installation. 

If no match is found then the integration creates a new Salesforce
contact object and populates its fields with data from Twitter.
If a match exists then the integration updates the matching Salesforce
contact object by using the values in the Twitter fields. 

To implement this sample integration, the main steps are:

. <<Register-With-Twitter>>.
. <<Register-With-Salesforce>>.
. <<Create-Twitter-Connection>>. 
. <<Create-SF-Connection-{reuse}>>. 
. <<Create-Twitter-SF-Integration>>.
. <<Confirm-Twitter-SF-Working>>.
. <<Clean-Up>>.

Before you implement this sample integration, 
see <<Twitter-Salesforce-Prerequisites>>.

include::t2sf_prereqs.adoc[leveloffset=+1]

include::t2sf_twitter_registration.adoc[leveloffset=+1]

include::t2sf_sf_registration.adoc[leveloffset=+1]

include::t2sf_create_twitter_conn.adoc[leveloffset=+1]

include::t2sf_create_sf_conn.adoc[leveloffset=+1]

include::t2sf_create_integration.adoc[leveloffset=+1]

include::t2sf_confirm_working.adoc[leveloffset=+1]

include::t2sf_clean_up.adoc[leveloffset=+1]
