[id='about-copying-integrations']
= About copying integrations

Each {prodname} installation is an environment from which you 
can export an integration. Exporting an integration downloads a zip file 
that contains the information needed to recreate the integration in a 
different environment.

When you import an integration the import operation creates each 
connection that the imported integration uses and copies all connection 
settings except for secrets. The import operation displays a list
of connections that require you to add configuration details, such as
secrets. You must edit each connection that is incomplete and ensure
that it is configured for its new environment. 

Reimporting an integration updates the integration, but does not update 
the connection settings that you specified in the import environment. 
The reimport operation creates any connections that are
new in the imported integration. 

When you import an integration it becomes the environment's draft 
integration. An environment can have exactly one draft integration.
 
