[id='about-api-client-connectors']
= About API client connectors

{prodname} can create connectors for application programming interfaces (APIs) 
that support the Hypertext Transfer Protocol (HTTP)/1.0 or HTTP/1.1 protocol.
To do this, {prodname} requires a valid
Swagger 2.0 specification that describes the API you want to connect to. 
If the API service provider does not make a Swagger specification available
then you must create the Swagger specification.
 
After you upload a Swagger specification to {prodname}, a connector to the API
becomes available. An integrator uses the connector to create
a connection and then selects that connection for use in an integration. 

When {prodname} creates an API client connector, it maps each resource 
operation in the Swagger specification to a connection action. The name
of the action is a combination of the resource path and the HTTP verb.
The action description comes from the corresponding documentation if 
it is available in the Swagger specification. 

{prodname} connectors support OAuth 1.0 and 2.0 and HTTP Basic
Authorization. If access to the API requires Transport Layer Security (TLS)
then the API needs to use a valid certificate that is issued by
a recognized Certificate Authority (CA).

{prodname} cannot create connectors for APIs that support the HTTP 2.0
protocol. 
