[id='add-basic-filter']
= Add a basic filter step

You can add a step to an integration to filter the data that the
integration operates on. In a filter step, {prodname} inspects the
data and continues the integration only if the content meets
criteria that you define. For example, in an integration that
obtains data from Twitter, you can specify that you want to
operate on data only when the tweet contains "Red Hat".

A filter determines which data from the input connection will reach the output connection. 

. On the *Create an Integration* page, click *Add a Step*

. Select *Basic Filter* from the *Add a Step* page. 

//There are a few questions here that need to be answered.
. On the *Configure filter step* page complete the configuration as follows:

.. Select from the dropdown to select whether to continue if the incoming data matches *all* of the filters defined below, or *any* of them. 

.. Next, select the field you want to use to control the filter. You can define the field in the following ways:
... Start typing. The data name field has a typeahead feature that will provide a list of possible completions for you in a pop-up box. Select the correct one from the box. 
... Click on the *text* field. A dropdown box will appear with a list of available fields. Select the field you require from the list.

.. Select an operation from the dropdown box. The setting defaults to *Contains*

.. Enter a value to filter on. For example, if you are trying to catch mentions of a certain product from the twitter feed, you would put the product name here.

. After you have completed your filter, you have an option to create another. Click on *+ Add another rule* to add another entry to your filter list. 
. You can delete an entry by clicking the trash can icon next to the entry. 

When you have completed your filter, click *Next >*.
