[id='export-import']
= Exporting and importing integrations

To deploy integrations across development, staging and 
production environments, you can export and import integrations.
The environments can all be on a single OpenShift cluster, 
or they can be spread out across multiple OpenShift clusters.

Every {prodname} installation is an environment from which you 
can export an integration. Exporting an integration downloads a zip file 
that contains the information needed to recreate the integration in a 
different environment.

When you import an integration the import operation creates each 
connection that the imported integration uses and copies all connection 
settings except for secrets. The import operation displays a list
of connections that require you to add configuration details, such as
secrets. You must edit each connection that is incomplete and ensure
that it is configured for its new environment. 

Reimporting an integration updates the integration, but does not update 
the connections. The reimport operation creates any connections that are
new in the imported integration. 

When you import an integration it because the environment's draft 
integration. An environment can have exactly one draft integration. 
