[id='logging-in-and-out']
= Logging in and out of {prodname}


When I click the link for my Ignite evaluation, I get a
Red Hat OpenShift Online Log In page
I log in using my Red Hat account

== Log In to an {prodname} Cluster using OpenShift's local Authentication.
To log in to a cluster that uses local Authentication provided by OpenShift, you are automatically redirected to the OpenShift log in screen.

=== First Time Log In
The first time you log in using OpenShift's local Authentication, you are prompted to provide the following credentials:

* Email address

* First name

* Last name

//verify this. Not sure what happens, really
The next time you log in you are prompted for the usual log in credentials.

== Log In to {prodname} Cluster Using GitHub Authentication
If you are logging in to a cluster that uses GitHub Authentication, there are two scenarios.

* If you are already signed in to GitHub then GitHub's Single Sign On facility
forwards you to {prodname}. 

* If you are not signed in to GitHub then the GitHub sign on screen appears.
you will be redirected to the GitHub sign on screen where you can enter your credentials.
//verify this
