:prodname: Syndesis
:prodversion: 1.0

[[User-Types]]
=== About {prodname} Users

{prodname} users are business experts in, for example, 
finance, human resources, or
marketing. They do not have the programming experience
typically required to share data between two different 
applications. Instead, their use of a
variety of software-as-a-service (SaaS) applications gives them an
understanding of business requirements, workflows and relevant data.

Sometimes referred to as citizen integrators, these business users might
be the only {prodname} users at a site. The {prodname}
web interface lets them configure built-in connectors, and create,
deploy and monitor integrations.

At some sites, a citizen integrator might collaborate with more
technical {prodname} users. These "expert" integrators have some programming
experience. Although they are comfortable using scripts to add logic
to applications, they do not work in integrated development
environments (IDEs). Expert integrators have some familiarity with
Camel enterprise integration patterns (EIPs) and they understand
protocols such as REST and SOAP. 

Expert integrators can assist citizen integrators if the need arises.

At some sites, there might be {prodname} developers. These users are
programmers who are familiar with Apache Camel and Maven.
Developers can use any Camel domain-specific language (DSL) to add
additional capabilities to an integration created by a citizen user.
Developers can create additional {prodname} connectors. 
