// Enable icons instead of text in admonitions (TIP, NOTE, and so on)
:icons:
:source-highlighter: pygments

[[style]]
= Style Guide for JBoss Fuse Documentation

[[style-boilerplate]]
== Boilerplate

[[style-headings]]
== Headings and Anchor IDs
The header for this subsection is defined as:

....
[[style-headings]] <1>
== Headings and Anchor IDs <2>
....

<1> The anchor ID is defined between square brackets (making it possible to link to this section).
<2> The header itself is defined using equals signs (where the number of signs indicates the depth).

NOTE: Do _not_ use the `#` symbol for defining headers (supported only for the sake of backward compatibility with Markdown syntax).

[[style-comments]]
== Comments in AsciiDoc
// This is a single line comment
Single line comments start with a double forward slash, like this:
....
// This is a single line comment
....

Multi-line comments are enclosed in a group of four forward slashes, like this:
....
////
This is a slightly longish
multi-line
comment.
////
....

[[style-blocks]]
== Paragraphs and Lists

[[style-blocks-paras]]
=== Paragraphs

[[style-blocks-itemized-list]]
=== Unordered List
A simple unordered list (bulleted list) is signalled by putting an asterisk at the start of each line, like this:

....
* First bullet.
* Second bullet.
* Third bullet.
....

Which renders as:

====
* First bullet.
* Second bullet.
* Third bullet.
====

One of the most useful things to know about unordered lists is how to add extra content to a bullet point without breaking out of the list?
The answer is to join the content with a `+` character (on its own line).

For example, consider the following unordered list:

....
* Launch the virtual machine with the following command:
+
----
$ vagrant up
----
+
NOTE: Make sure that you run this command in the same directory as the `Vagrantfile` file

* Shut down the virtual machine with the following command:
+
----
$ vagrant halt
----
....

Which renders as:

====
* Launch the virtual machine with the following command:
+
----
$ vagrant up
----
+
NOTE: Make sure that run this command in the same directory as the `Vagrantfile` file

* Shut down the virtual machine with the following command:
+
----
$ vagrant halt
----
====

[[style-blocks-ordered-list]]
=== Ordered List
An ordered list (numbered list) is signaled by putting a dot, `.`, at the start of each line. Once again, to join content and keep it in the same numbered point, use a the `+` character.

For example, consider the following ordered list:

....
. Log in to OpenShift by entering the following command:
+
----
$ oc login -u admin -p admin
----
+
NOTE: The `admin` user account is created by default in the CDK.

. Switch to the `test` project by entering the following command:
+
----
$ oc project test
----
....

Which renders as:

====
. Log in to OpenShift by entering the following command:
+
----
$ oc login -u admin -p admin
----
+
NOTE: The `admin` user account is created by default in the CDK.

. Switch to the `test` project by entering the following command:
+
----
$ oc project test
----
====

[[style-blocks-variable-list]]
=== Variable List
The variable list is a great layout to use when you need to present a list of terms and associated descriptions (and is often a superior alternative to using a bulleted list).

For example, consider the following variable list:

....
OpenShift client:: If you are using the CDK, the `oc` client tool can conveniently be installed as follows:
+
----
$ vagrant service-manager install-cli openshift
----

Docker client:: If you are using the CDK, the `docker` client tool can conveniently be installed as follows:
+
----
$ vagrant service-manager install-cli docker
----
....

Which renders as:

====
OpenShift client:: If you are using the CDK, the `oc` client tool can conveniently be installed as follows:
+
----
$ vagrant service-manager install-cli openshift
----

Docker client:: If you are using the CDK, the `docker` client tool can conveniently be installed as follows:
+
----
$ vagrant service-manager install-cli docker
----
====

[[style-code]]
== Code Formatting

[[style-code-inline]]
=== Inline Code
Use backticks to enclose inline code.

For example, to start the fuse container, enter the `./bin/fuse` command.

----
For example, to start the fuse container, enter the `./bin/fuse` command.
----

You can use `_underscores inside backticks_` or `*asterisks inside backticks*`. But if you prefer the underscore or asterisk to be shown literally, `\_escape the first one with a backslash_`.

----
You can use `_underscores inside backticks_` or `*asterisks inside backticks*`. But if you prefer the underscore or asterisk to be shown literally, `\_escape the first one with a backslash_`.
----


[[style-code-listing-notitle]]
=== Code Listing without Title
You _could_ create a code listing by putting spaces at the start of each line of code, but _this approach is deprecated._

It is much better to delimit a code block by putting a line with four hyphens `----` at the beginning and end of the listing, like this:

....
----
oc login -u admin -p admin
----
....

Which renders as:
====
----
oc login -u admin -p admin
----
====

If you are presenting a snippet of XML code, it is strongly recommended to switch on syntax highlighting, like this:

....
[source,xml]
----
<repositories>
  <repository>
    <id>foo</id>
  </repository>
</repositories>
----
....

Which renders as:

====
[source,xml]
----
<repositories>
  <repository>
    <id>foo</id>
  </repository>
</repositories>
----
====

Likewise, for Java code snippets it is highly recommended to switch on syntax highlighting like this:

....
[source,java]
----
class FooBar {
  int getNumberOfFoos();
  void setNumberOfFoos();
}
----
....

Which renders as:

====
[source,java]
----
class FooBar {
  int getNumberOfFoos();
  void setNumberOfFoos();
}
----
====

[[style-code-listing-title]]
=== Code Listing with Title
To define a code listing with a title, precede it with a title line like `.This is a Code Example`.
And if you are giving a code listing a title, it is generally a good idea to assign an anchor ID (between `[[` and `]]`) as well and to put it in a generic block (enclosed in `====` lines). For example:

....
[[style-code-xml-example]]
.Code Caption
====
[source,xml]
----
<repositories>
  <repository>
    <id>foo</id>
  </repository>
</repositories>
----
====
....

Which renders as:

[[style-code-xml-example]]
.Code Caption
====
[source,xml]
----
<repositories>
  <repository>
    <id>foo</id>
  </repository>
</repositories>
----
====

And because you have given the listing an anchor ID, you can easily cross-reference the <<style-code-xml-example>>.


[[style-code-callouts]]
=== Code Listing That Has Callouts and Italics
Sometimes a code listing uses callouts and also italics for placeholders. 
To be able to insert callouts and also preserve italics, 
insert `[subs="+quotes"]` before the code listing. 

[[style-code-listing-attribute-sub]]
=== Attribute Substitution in Code Listings
There are circumstances where it can be useful to substitutes attribute values inside code listings.
By default, this is not possible because the curly braces, `{}`, are interpreted literally inside a code listing.
But if you specify `[subs="attributes"]` at the start of the listing, attribute substitution _is_ performed. For example:

....
[subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeCatalog={archetype-catalog} \
  -DarchetypeGroupId=org.jboss.fuse.fis.archetypes \
  -DarchetypeArtifactId=spring-boot-camel-archetype \
  -DarchetypeVersion={archetype-version}
----
....

Which renders as:

:archetype-version: 2.2.180.fuse-000003
:archetype-catalog: https://repository.jboss.org/nexus/content/groups/ea/archetype-catalog.xml

[subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeCatalog={archetype-catalog} \
  -DarchetypeGroupId=org.jboss.fuse.fis.archetypes \
  -DarchetypeArtifactId=spring-boot-camel-archetype \
  -DarchetypeVersion={archetype-version}
----

[[style-gui]]
== GUI Item Formatting

Enclose GUI items in asterisks. This includes menu selections, 
dialog titles, button labels, popup selections and any other text that 
appears in a GUI. The asterisks make the item appear in bold font. 

To format a sequence of selections, separate the items with a hyphen
followed by a greater than symbol. For example:

----
Select *File* -> *Open* -> *New*
----

This renders as:

Select *File* -> *Open* -> *New*





[[style-images]]
== Images and Figures

[[style-images-inline]]
=== Inline Image

[[style-images-nocaption]]
=== Image without Caption

[[style-images-caption]]
=== Image with Caption

[[style-linking]]
== Linking and Cross Referencing
This section gives some recommendations for hyperlinking (HTTP link to an external resource) and cross referencing (linking to a location in the same book or in a different book in the same library).

[[style-linking-url]]
=== Hyperlinks
Creating a hyperlink (HTTP URL) in AsciiDoc could not be simpler.
HTTP URLs and HTTPS URLs (and a few other URL schemes) are automatically converted to hyperlinks.

For example, the following HTTP URL:

....
https://camel.apache.org/rest-dsl.html
....

Renders as:

https://camel.apache.org/rest-dsl.html

If you want to specify the link text, just add square braces at the end of the URL. For example:

....
https://camel.apache.org/rest-dsl.html[REST DSL upstream documentation]
....

Which renders as:

https://camel.apache.org/rest-dsl.html[REST DSL upstream documentation]

You can optionally prefix the HTTP URL with `link:` (as in `link:https://camel.apache.org/rest-dsl.html`), but it's _not_ necessary.

[[style-linking-xref]]
=== Cross Referencing within the Same Book
To cross reference a location within the same book, all you need is the anchor ID of the location (which could be a section, code example, figure, and so on). There are two alternative syntaxes for defining a cross-references and they are both equally good.

For example, here are two links to the same location with anchor ID `style-code-xml-example`:

....
See <<style-code-xml-example>>

See xref:style-code-xml-example[]
....

Which render as:

====
See <<style-code-xml-example>>

See xref:style-code-xml-example[]
====

If you want AsciiDoc to provide the link text automatically, you must be careful how you position the anchor ID at the target location.
Make sure that the anchor ID appears just before the title of the item you are referencing. For example, this is the right way to add the anchor to a code example:

....
[[style-code-xml-example]]
.Code Caption
====
[source,xml]
----
<repositories>
  <repository>
    <id>foo</id>
  </repository>
</repositories>
----
====
....

You might come across a variant of the cross reference syntax that includes the file name of the location you want to reference, as follows:

....
See <<style_guide.adoc#style-code-xml-example>>
....


_Do not use this syntax to reference a location in the same book!_
It looks like a plausible thing to do, if the target location is in a different file.
But it is bad, because it means that any time you move or rename the file, all of its associated cross references will be broken. It is not necessary to include the file name anyway, because when you build the whole book AsciiDoc will be able to resolve the cross references (even without the file name).

[[style-structure]]
== Document Structure and Includes

=== Indexes

To include an index in the generated document, add the following at the end of the `master.adoc file`:

----
[index, id='ix01']
= Index: value
----

This assumes that there are index entries in the source files. 
